apiVersion: v1
kind: Secret
metadata:
    name: bws-secret
stringData:
    token: ENC[AES256_GCM,data:SekB5IUGL7/Ok/coL7Tu+UgQr7nLczs1JcrBNyx4leKD1agAZIckqQB4WYyKOq+pFImrhCTgDqAgzG0qpgsWjbuEM9jeCOJ8GDDuL32YHym9EYhrpFttR40XvfY7rw==,iv:w8utTbDwMgYlOonhWXXLv7AYEnH0uUQ+G2XCQHO1Ads=,tag:g+Msk1kQR9O5kLn/9L4MZw==,type:str]
    ORG_ID: ENC[AES256_GCM,data:EiLCpLO0epNYn4Vc2y3GCBHa/fd8tyOzd/JFUd89kvoLG3Fq,iv:vcT6KtcXpghiqmA2ZbNYubaeqlSanFTRTNeoxk1VG88=,tag:spNsySCebrzNkzMcpLcdvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msszvdvy3x8wlm8zkkdnuwvh968fuk2xnmcp6jepuzthwgarq90sksenah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMG02ZUs1ci8xbHBoUHZ0
            V0YyRzRIdlJXME5XVisrclZzNHBZN1FkUGx3Ck1NNlZoSGNNTVdhSjczbTBPRlNE
            ckxSeGFoQkUwMXM3NXRoUlYrZTkyOTQKLS0tICtpemlRNlZHeUhOTHY3bVZoL1RX
            TU1PVkxFa1F0citOWGttQkt0SVJWWU0KsUD7Y+aIKGOCzWYeY2pi35OlGOEXfy7i
            zXhCod1a2OhcWOrTOC1QgxFvcYE7ldcOE5q3/43fW4kxlCd84rhtvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-27T20:58:13Z"
    mac: ENC[AES256_GCM,data:xAN6UVtDojDsVAc8FjnYv/mv4HYQIA7oYnznEd9NcCqVcAGePHWohkJciMQ/V1t/TOKayAwzfD/rnDuVXs5Qvo6ll/M2MOBdQMApHwaxR5qKgOm/dbY0CYSMT0N79z7EUj/DvtvrcbXhwdMVIuWRVg7EnJ5/RFFqhXIp85WNlR0=,iv:mx83baEikT5Viu+m3Kb4ke1QnfsDd+EKz9l/hgoMobA=,tag:AM7MFG/tHh33E3SnGTpA7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
