---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-generator
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "harbor-encryption"
spec:
  target:
    name: harbor-encryption-secret
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password-generator
      rewrite:
        - transform:
            template: secretKey
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "harbor"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: harbor-secret
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: harbor
