---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  dependsOn:
    - name: openebs
      namespace: openebs-system
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: tls.harbor
      ingress:
        className: external
        hosts: ["core.${SECRET_DOMAIN}"]
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      externalURL: https://harbor.${SECRET_DOMAIN}
    ipFamily:
      ipv6:
        enabled: false
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          existingClaim: harbor-registry-v1
          storageClass: openebs-hostpath
          subPath: registry
        jobservice:
          jobLog:
            storageClass: openebs-hostpath
            size: 1Gi
        database:
          storageClass: openebs-hostpath
          size: 1Gi
        redis:
          storageClass: openebs-hostpath
          size: 1Gi
        trivy:
          storageClass: openebs-hostpath
          size: 5Gi

    database:
      type: internal

#      imageChartStorage:
#        type: s3
#        s3:
#          bucket: kubernetes-registry
#          accesskey: ${AWS_SECRET_KEY_ID}
#          secretkey: ${AWS_SECRET_KEY}
#          regionendpoint: https://${SECRET_BACKUP_SERVER}
#          rootdirectory: /prod

#    # our CSI does not support ReadWriteMany so we must use Recreate on pods
#    updateStrategy:
#      type: Recreate

    existingSecretAdminPassword: harbor-secret
    existingSecretAdminPasswordKey: password
    secretKey:
    existingSecretSecretKey: harbor-encryption-secret

    notary:
      enabled: false

    nginx:
      podAnnotations:
        secret.reloader.stakater.com/reload: tls.harbor
