---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-v1
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: openebs-hostpath
