---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: postgres-connection-string
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres-connection-string-secret
  data:
  - secretKey: ConnectionStrings__existingPostgres
    remoteRef:
      key: postgres-connection
