---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etymo
spec:
  interval: 30m
  chart:
    spec:
      chart: etymo
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: etymo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3