---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etymo
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: etymo
      version: 0.0.1-302
      sourceRef:
        kind: HelmRepository
        name: etymo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    expose:
      webfrontend:
        ingress:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          ingressClassName: external
          hosts: ["etymo.${SECRET_DOMAIN}"]
        externalUrl: "https://etymo.${SECRET_DOMAIN}/"
      keycloak:
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          ingressClassName: internal
          hosts: ["sso.etymo.${SECRET_DOMAIN}"]
          tls:
            - hosts:
                - "sso.etymo.${SECRET_DOMAIN}"
              secretName: "tls.keycloak"
    secrets:
      connectionStrings:
        existingPostgres: postgres-connection-string-secret/ConnectionStrings__existingPostgres
