---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etymo
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: etymo
      version: 0.0.1-118
      sourceRef:
        kind: HelmRepository
        name: etymo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    expose:
      webfrontend:
        ingress:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          ingressClassName: internal
          hosts: ["etymo.${SECRET_DOMAIN}"]
          pathType: Prefix
        externalUrl: "https://etymo.${SECRET_DOMAIN}/"