---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sf-gamedata
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath