---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    nameOverride: *app
    provider:
      name: cloudflare
    cloudflare:
      apiToken:
        secretRef:
          name: external-dns-secret
          key: api-token
      proxied: true

    extraArgs:
      - --ingress-class=external
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint

    policy: sync
    sources: ["crd", "ingress"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: ["${SECRET_DOMAIN}"]

    serviceMonitor:
      enabled: true

    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret
