apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:VMg3aD+NmeyHETzgSpi/r5VUYaPZWT8TJPSyCFrsbia5tmg2okgd8A==,iv:a+HeGBjggfGq/d9dGbOTJWA1hEUkkltDQ6dAbNHVozc=,tag:8DLknx+mCzE++GIHvaiWvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msszvdvy3x8wlm8zkkdnuwvh968fuk2xnmcp6jepuzthwgarq90sksenah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMTdia0lOTGhaQTJiVk9z
            cm9HZW1KR2xMV25kYVVnbnlmT28rZ2hLNms4CnVvYzRjTlR2ellsOVJzYXhxTmVm
            SEx6dFNqY3JJWHh2ZWsyTUZCME01RzAKLS0tIHA1VGJVVG1ocGNqQzA0YXhubFNE
            dlVQaXRINDNwUHFoM2NkeTZ0VjhMcUEKqY2YRxRH6j2SC7IBzXXDl/EisRj7EUvh
            IAyIKOniJf70655J1rvW6vgfkAP8LGrnKy6ldJ+THVOQMkwO0qnaiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T00:34:35Z"
    mac: ENC[AES256_GCM,data:rbHaXQn66WM+cCB9wknAlnHpS2oco+RODvE5bg3ymXv/7PZjwyHh1ots2moFolPpTZnvUHJ2eU9Jx7mqaXXaoLTScvNTNM9G4py3yZYyMqT6AerLZalMR6/vFYd3CNE+dXy08Q7fFLm4CK6gh1qZo4KLGqwOMARgI7WP5wsW9IE=,iv:DevxQfK7uNDBARPI3+9Y7CWPkaUDes5hhnMH5yVF0/g=,tag:gSiV270sfdACTEPR92adQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
